version: "3"

services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DBHOST: "postgres"
      DBPORT: "5432"
      DBUSER: "shop"
      DBPASS: "shop"
      DBNAME: "shop"
      SSLMODE: "disable"
    volumes:
      - ../../:/src
    working_dir: "/src"
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    ports:
      - "1323:1323"
    networks:
      - network

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "shop"
      POSTGRES_PASSWORD: "shop"
      POSTGRES_DBNAME: "shop"
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      - network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "6543:80"
    depends_on:
      - postgres
    networks:
      - network

volumes:
  data:

networks:
  network:
    driver: bridge