// Code generated by go-swagger; DO NOT EDIT.

package car

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFindAllCarsParams creates a new FindAllCarsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFindAllCarsParams() *FindAllCarsParams {
	return &FindAllCarsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFindAllCarsParamsWithTimeout creates a new FindAllCarsParams object
// with the ability to set a timeout on a request.
func NewFindAllCarsParamsWithTimeout(timeout time.Duration) *FindAllCarsParams {
	return &FindAllCarsParams{
		timeout: timeout,
	}
}

// NewFindAllCarsParamsWithContext creates a new FindAllCarsParams object
// with the ability to set a context for a request.
func NewFindAllCarsParamsWithContext(ctx context.Context) *FindAllCarsParams {
	return &FindAllCarsParams{
		Context: ctx,
	}
}

// NewFindAllCarsParamsWithHTTPClient creates a new FindAllCarsParams object
// with the ability to set a custom HTTPClient for a request.
func NewFindAllCarsParamsWithHTTPClient(client *http.Client) *FindAllCarsParams {
	return &FindAllCarsParams{
		HTTPClient: client,
	}
}

/* FindAllCarsParams contains all the parameters to send to the API endpoint
   for the find all cars operation.

   Typically these are written to a http.Request.
*/
type FindAllCarsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the find all cars params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindAllCarsParams) WithDefaults() *FindAllCarsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the find all cars params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindAllCarsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the find all cars params
func (o *FindAllCarsParams) WithTimeout(timeout time.Duration) *FindAllCarsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find all cars params
func (o *FindAllCarsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find all cars params
func (o *FindAllCarsParams) WithContext(ctx context.Context) *FindAllCarsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find all cars params
func (o *FindAllCarsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find all cars params
func (o *FindAllCarsParams) WithHTTPClient(client *http.Client) *FindAllCarsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find all cars params
func (o *FindAllCarsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *FindAllCarsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
